angular.module("app.core",
[
    "kendo.directives",
    "app.drive",
    "app.vacation",
    "ui.router",
    "ui.bootstrap",
    "ui.bootstrap.tooltip",
    "ngResource",
    "template/modal/window.html",
    "template/modal/window.html",
    "template/modal/backdrop.html",
    "template/tabs/tab.html",
    "template/tabs/tabset.html",
    "angularMoment",
    "template/popover/popover.html",
    "kendo-ie-fix",
    "angular-loading-bar"
]);