//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medarbejder
    {
        public Nullable<int> MaNr { get; set; }
        public Nullable<System.DateTime> Ansaettelsesdato { get; set; }
        public Nullable<System.DateTime> Ophoersdato { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public string ADBrugerNavn { get; set; }
        public string Adresse { get; set; }
        public string Stednavn { get; set; }
        public string PostNr { get; set; }
        public string By { get; set; }
        public string Land { get; set; }
        public string email { get; set; }
        public string CPR { get; set; }
        public Nullable<int> LOSOrgId { get; set; }
        public bool Leder { get; set; }
        public string Stillingsbetegnelse { get; set; }
        public Nullable<long> Omkostningssted { get; set; }
        public string AnsatForhold { get; set; }
        public Nullable<short> EkstraCiffer { get; set; }
    }
}
