//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", ConfigurationName="GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI")]
    public interface GetAbsenceAttendanceByPeriod_OS_SI {
        
        // CODEGEN: Generating message contract since the operation GetAbsenceAttendanceByPeriod_OS_SI is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIResponse GetAbsenceAttendanceByPeriod_OS_SI(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIResponse> GetAbsenceAttendanceByPeriod_OS_SIAsync(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vendorUUIDField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string personnelNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VendorUUID {
            get {
                return this.vendorUUIDField;
            }
            set {
                this.vendorUUIDField = value;
                this.RaisePropertyChanged("VendorUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PersonnelNumber {
            get {
                return this.personnelNumberField;
            }
            set {
                this.personnelNumberField = value;
                this.RaisePropertyChanged("PersonnelNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetAbsenceAttendanceByPeriodResponseItem[] returnStatusField;
        
        private GetAbsenceAttendanceByPeriodResponseItem1[] absenceAttendanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetAbsenceAttendanceByPeriodResponseItem[] ReturnStatus {
            get {
                return this.returnStatusField;
            }
            set {
                this.returnStatusField = value;
                this.RaisePropertyChanged("ReturnStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetAbsenceAttendanceByPeriodResponseItem1[] AbsenceAttendance {
            get {
                return this.absenceAttendanceField;
            }
            set {
                this.absenceAttendanceField = value;
                this.RaisePropertyChanged("AbsenceAttendance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusTypeField;
        
        private string messageClassField;
        
        private string messageNumberField;
        
        private string messageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
                this.RaisePropertyChanged("StatusType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MessageClass {
            get {
                return this.messageClassField;
            }
            set {
                this.messageClassField = value;
                this.RaisePropertyChanged("MessageClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MessageNumber {
            get {
                return this.messageNumberField;
            }
            set {
                this.messageNumberField = value;
                this.RaisePropertyChanged("MessageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("MessageText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItem1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetAbsenceAttendanceByPeriodResponseItemKey keyField;
        
        private GetAbsenceAttendanceByPeriodResponseItemItem itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetAbsenceAttendanceByPeriodResponseItemKey Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GetAbsenceAttendanceByPeriodResponseItemItem Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItemKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personnelNumberField;
        
        private string absenceAttendanceTypeField;
        
        private string objectIdField;
        
        private string lockIndicatorField;
        
        private string endDateField;
        
        private string startDateField;
        
        private string recordNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PersonnelNumber {
            get {
                return this.personnelNumberField;
            }
            set {
                this.personnelNumberField = value;
                this.RaisePropertyChanged("PersonnelNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AbsenceAttendanceType {
            get {
                return this.absenceAttendanceTypeField;
            }
            set {
                this.absenceAttendanceTypeField = value;
                this.RaisePropertyChanged("AbsenceAttendanceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("ObjectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LockIndicator {
            get {
                return this.lockIndicatorField;
            }
            set {
                this.lockIndicatorField = value;
                this.RaisePropertyChanged("LockIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RecordNumber {
            get {
                return this.recordNumberField;
            }
            set {
                this.recordNumberField = value;
                this.RaisePropertyChanged("RecordNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItemItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personnelNumberField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private string absenceAttendanceTypeField;
        
        private string absenceAttendanceTypeTextField;
        
        private string absenceAttendanceDaysField;
        
        private string absenceAttendanceHoursField;
        
        private string absenceAttendanceCalendarDaysField;
        
        private GetAbsenceAttendanceByPeriodResponseItemItemItem[] maternityField;
        
        private GetAbsenceAttendanceByPeriodResponseItemItemItem1[] reasonField;
        
        private GetAbsenceAttendanceByPeriodResponseItemItemItem2[] workInjuryField;
        
        private GetAbsenceAttendanceByPeriodResponseItemItemItem3[] compLeaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PersonnelNumber {
            get {
                return this.personnelNumberField;
            }
            set {
                this.personnelNumberField = value;
                this.RaisePropertyChanged("PersonnelNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AbsenceAttendanceType {
            get {
                return this.absenceAttendanceTypeField;
            }
            set {
                this.absenceAttendanceTypeField = value;
                this.RaisePropertyChanged("AbsenceAttendanceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AbsenceAttendanceTypeText {
            get {
                return this.absenceAttendanceTypeTextField;
            }
            set {
                this.absenceAttendanceTypeTextField = value;
                this.RaisePropertyChanged("AbsenceAttendanceTypeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AbsenceAttendanceDays {
            get {
                return this.absenceAttendanceDaysField;
            }
            set {
                this.absenceAttendanceDaysField = value;
                this.RaisePropertyChanged("AbsenceAttendanceDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string AbsenceAttendanceHours {
            get {
                return this.absenceAttendanceHoursField;
            }
            set {
                this.absenceAttendanceHoursField = value;
                this.RaisePropertyChanged("AbsenceAttendanceHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string AbsenceAttendanceCalendarDays {
            get {
                return this.absenceAttendanceCalendarDaysField;
            }
            set {
                this.absenceAttendanceCalendarDaysField = value;
                this.RaisePropertyChanged("AbsenceAttendanceCalendarDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetAbsenceAttendanceByPeriodResponseItemItemItem[] Maternity {
            get {
                return this.maternityField;
            }
            set {
                this.maternityField = value;
                this.RaisePropertyChanged("Maternity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetAbsenceAttendanceByPeriodResponseItemItemItem1[] Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetAbsenceAttendanceByPeriodResponseItemItemItem2[] WorkInjury {
            get {
                return this.workInjuryField;
            }
            set {
                this.workInjuryField = value;
                this.RaisePropertyChanged("WorkInjury");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetAbsenceAttendanceByPeriodResponseItemItemItem3[] CompLeave {
            get {
                return this.compLeaveField;
            }
            set {
                this.compLeaveField = value;
                this.RaisePropertyChanged("CompLeave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItemItemItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maternityCaseKeyField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string notificationDateField;
        
        private string expectedDeliveryDateField;
        
        private string actualDeliveryDateField;
        
        private string authorityReportDateField;
        
        private string maternityTypeField;
        
        private string maternityTypeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MaternityCaseKey {
            get {
                return this.maternityCaseKeyField;
            }
            set {
                this.maternityCaseKeyField = value;
                this.RaisePropertyChanged("MaternityCaseKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NotificationDate {
            get {
                return this.notificationDateField;
            }
            set {
                this.notificationDateField = value;
                this.RaisePropertyChanged("NotificationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ExpectedDeliveryDate {
            get {
                return this.expectedDeliveryDateField;
            }
            set {
                this.expectedDeliveryDateField = value;
                this.RaisePropertyChanged("ExpectedDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ActualDeliveryDate {
            get {
                return this.actualDeliveryDateField;
            }
            set {
                this.actualDeliveryDateField = value;
                this.RaisePropertyChanged("ActualDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AuthorityReportDate {
            get {
                return this.authorityReportDateField;
            }
            set {
                this.authorityReportDateField = value;
                this.RaisePropertyChanged("AuthorityReportDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MaternityType {
            get {
                return this.maternityTypeField;
            }
            set {
                this.maternityTypeField = value;
                this.RaisePropertyChanged("MaternityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MaternityTypeText {
            get {
                return this.maternityTypeTextField;
            }
            set {
                this.maternityTypeTextField = value;
                this.RaisePropertyChanged("MaternityTypeText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItemItemItem1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string reasonCodeField;
        
        private string reasonCodeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("ReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReasonCodeText {
            get {
                return this.reasonCodeTextField;
            }
            set {
                this.reasonCodeTextField = value;
                this.RaisePropertyChanged("ReasonCodeText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItemItemItem2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accidentNumberField;
        
        private string accidentDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AccidentNumber {
            get {
                return this.accidentNumberField;
            }
            set {
                this.accidentNumberField = value;
                this.RaisePropertyChanged("AccidentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AccidentDate {
            get {
                return this.accidentDateField;
            }
            set {
                this.accidentDateField = value;
                this.RaisePropertyChanged("AccidentDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetAbsenceAttendanceByPeriodResponseItemItemItem3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string childNumberField;
        
        private string childCPRNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ChildNumber {
            get {
                return this.childNumberField;
            }
            set {
                this.childNumberField = value;
                this.RaisePropertyChanged("ChildNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ChildCPRNumber {
            get {
                return this.childCPRNumberField;
            }
            set {
                this.childCPRNumberField = value;
                this.RaisePropertyChanged("ChildCPRNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAbsenceAttendanceByPeriod_OS_SIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", Order=0)]
        public Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodRequest GetAbsenceAttendanceByPeriodRequest_MT;
        
        public GetAbsenceAttendanceByPeriod_OS_SIRequest() {
        }
        
        public GetAbsenceAttendanceByPeriod_OS_SIRequest(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodRequest GetAbsenceAttendanceByPeriodRequest_MT) {
            this.GetAbsenceAttendanceByPeriodRequest_MT = GetAbsenceAttendanceByPeriodRequest_MT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAbsenceAttendanceByPeriod_OS_SIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", Order=0)]
        public Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodResponse GetAbsenceAttendanceByPeriodResponse_MT;
        
        public GetAbsenceAttendanceByPeriod_OS_SIResponse() {
        }
        
        public GetAbsenceAttendanceByPeriod_OS_SIResponse(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodResponse GetAbsenceAttendanceByPeriodResponse_MT) {
            this.GetAbsenceAttendanceByPeriodResponse_MT = GetAbsenceAttendanceByPeriodResponse_MT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetAbsenceAttendanceByPeriod_OS_SIChannel : Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAbsenceAttendanceByPeriod_OS_SIClient : System.ServiceModel.ClientBase<Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI>, Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI {
        
        public GetAbsenceAttendanceByPeriod_OS_SIClient() {
        }
        
        public GetAbsenceAttendanceByPeriod_OS_SIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAbsenceAttendanceByPeriod_OS_SIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAbsenceAttendanceByPeriod_OS_SIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAbsenceAttendanceByPeriod_OS_SIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIResponse Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI.GetAbsenceAttendanceByPeriod_OS_SI(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest request) {
            return base.Channel.GetAbsenceAttendanceByPeriod_OS_SI(request);
        }
        
        public Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodResponse GetAbsenceAttendanceByPeriod_OS_SI(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodRequest GetAbsenceAttendanceByPeriodRequest_MT) {
            Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest inValue = new Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest();
            inValue.GetAbsenceAttendanceByPeriodRequest_MT = GetAbsenceAttendanceByPeriodRequest_MT;
            Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIResponse retVal = ((Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI)(this)).GetAbsenceAttendanceByPeriod_OS_SI(inValue);
            return retVal.GetAbsenceAttendanceByPeriodResponse_MT;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIResponse> Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI.GetAbsenceAttendanceByPeriod_OS_SIAsync(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest request) {
            return base.Channel.GetAbsenceAttendanceByPeriod_OS_SIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIResponse> GetAbsenceAttendanceByPeriod_OS_SIAsync(Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriodRequest GetAbsenceAttendanceByPeriodRequest_MT) {
            Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest inValue = new Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SIRequest();
            inValue.GetAbsenceAttendanceByPeriodRequest_MT = GetAbsenceAttendanceByPeriodRequest_MT;
            return ((Infrastructure.KMDVacationService.GetAbsenceAttendanceByPeriod.GetAbsenceAttendanceByPeriod_OS_SI)(this)).GetAbsenceAttendanceByPeriod_OS_SIAsync(inValue);
        }
    }
}
