//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.KMDVacationService.GetMaternityCases {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", ConfigurationName="GetMaternityCases.GetMaternityCases_OS_SI")]
    public interface GetMaternityCases_OS_SI {
        
        // CODEGEN: Generating message contract since the operation GetMaternityCases_OS_SI is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIResponse GetMaternityCases_OS_SI(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIResponse> GetMaternityCases_OS_SIAsync(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetMaternityCasesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maternityTypeField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string personnelNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MaternityType {
            get {
                return this.maternityTypeField;
            }
            set {
                this.maternityTypeField = value;
                this.RaisePropertyChanged("MaternityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PersonnelNumber {
            get {
                return this.personnelNumberField;
            }
            set {
                this.personnelNumberField = value;
                this.RaisePropertyChanged("PersonnelNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetMaternityCasesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetMaternityCasesResponseReturnStatus returnStatusField;
        
        private GetMaternityCasesResponseItem[] maternityCaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetMaternityCasesResponseReturnStatus ReturnStatus {
            get {
                return this.returnStatusField;
            }
            set {
                this.returnStatusField = value;
                this.RaisePropertyChanged("ReturnStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetMaternityCasesResponseItem[] MaternityCase {
            get {
                return this.maternityCaseField;
            }
            set {
                this.maternityCaseField = value;
                this.RaisePropertyChanged("MaternityCase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetMaternityCasesResponseReturnStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusTypeField;
        
        private string messageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
                this.RaisePropertyChanged("StatusType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("MessageText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:kmd.dk:LPT:VACAB:external")]
    public partial class GetMaternityCasesResponseItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personnelNumberField;
        
        private string maternityCaseKeyField;
        
        private string validEndDateField;
        
        private string validStartDateField;
        
        private string notificationDateField;
        
        private string expectedDeliveryDateField;
        
        private string actualDeliveryDateField;
        
        private string authorityReportDateField;
        
        private string maternityTypeField;
        
        private string maternityTypeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PersonnelNumber {
            get {
                return this.personnelNumberField;
            }
            set {
                this.personnelNumberField = value;
                this.RaisePropertyChanged("PersonnelNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MaternityCaseKey {
            get {
                return this.maternityCaseKeyField;
            }
            set {
                this.maternityCaseKeyField = value;
                this.RaisePropertyChanged("MaternityCaseKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ValidEndDate {
            get {
                return this.validEndDateField;
            }
            set {
                this.validEndDateField = value;
                this.RaisePropertyChanged("ValidEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ValidStartDate {
            get {
                return this.validStartDateField;
            }
            set {
                this.validStartDateField = value;
                this.RaisePropertyChanged("ValidStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NotificationDate {
            get {
                return this.notificationDateField;
            }
            set {
                this.notificationDateField = value;
                this.RaisePropertyChanged("NotificationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ExpectedDeliveryDate {
            get {
                return this.expectedDeliveryDateField;
            }
            set {
                this.expectedDeliveryDateField = value;
                this.RaisePropertyChanged("ExpectedDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ActualDeliveryDate {
            get {
                return this.actualDeliveryDateField;
            }
            set {
                this.actualDeliveryDateField = value;
                this.RaisePropertyChanged("ActualDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AuthorityReportDate {
            get {
                return this.authorityReportDateField;
            }
            set {
                this.authorityReportDateField = value;
                this.RaisePropertyChanged("AuthorityReportDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MaternityType {
            get {
                return this.maternityTypeField;
            }
            set {
                this.maternityTypeField = value;
                this.RaisePropertyChanged("MaternityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MaternityTypeText {
            get {
                return this.maternityTypeTextField;
            }
            set {
                this.maternityTypeTextField = value;
                this.RaisePropertyChanged("MaternityTypeText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaternityCases_OS_SIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", Order=0)]
        public Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesRequest GetMaternityCasesRequest_MT;
        
        public GetMaternityCases_OS_SIRequest() {
        }
        
        public GetMaternityCases_OS_SIRequest(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesRequest GetMaternityCasesRequest_MT) {
            this.GetMaternityCasesRequest_MT = GetMaternityCasesRequest_MT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaternityCases_OS_SIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", Order=0)]
        public Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesResponse GetMaternityCasesResponse_MT;
        
        public GetMaternityCases_OS_SIResponse() {
        }
        
        public GetMaternityCases_OS_SIResponse(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesResponse GetMaternityCasesResponse_MT) {
            this.GetMaternityCasesResponse_MT = GetMaternityCasesResponse_MT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetMaternityCases_OS_SIChannel : Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMaternityCases_OS_SIClient : System.ServiceModel.ClientBase<Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI>, Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI {
        
        public GetMaternityCases_OS_SIClient() {
        }
        
        public GetMaternityCases_OS_SIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetMaternityCases_OS_SIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMaternityCases_OS_SIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMaternityCases_OS_SIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIResponse Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI.GetMaternityCases_OS_SI(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest request) {
            return base.Channel.GetMaternityCases_OS_SI(request);
        }
        
        public Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesResponse GetMaternityCases_OS_SI(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesRequest GetMaternityCasesRequest_MT) {
            Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest inValue = new Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest();
            inValue.GetMaternityCasesRequest_MT = GetMaternityCasesRequest_MT;
            Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIResponse retVal = ((Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI)(this)).GetMaternityCases_OS_SI(inValue);
            return retVal.GetMaternityCasesResponse_MT;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIResponse> Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI.GetMaternityCases_OS_SIAsync(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest request) {
            return base.Channel.GetMaternityCases_OS_SIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIResponse> GetMaternityCases_OS_SIAsync(Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCasesRequest GetMaternityCasesRequest_MT) {
            Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest inValue = new Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SIRequest();
            inValue.GetMaternityCasesRequest_MT = GetMaternityCasesRequest_MT;
            return ((Infrastructure.KMDVacationService.GetMaternityCases.GetMaternityCases_OS_SI)(this)).GetMaternityCases_OS_SIAsync(inValue);
        }
    }
}
