//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.KMDVacationService.KMD_FerieService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kmd.dk:LPT:VACAB:external", ConfigurationName="KMD_FerieService.LPT_VACAB_Service_Out")]
    public interface LPT_VACAB_Service_Out {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message GET_EMPLOYEE_INFORequest does not match the default value (urn:kmd.dk:LPT:VACAB:external)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFOResponse GET_EMPLOYEE_INFO(Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFOResponse> GET_EMPLOYEE_INFOAsync(Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message SET_ABSENCE_PULSRequest does not match the default value (urn:kmd.dk:LPT:VACAB:external)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSResponse SET_ABSENCE_PULS(Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSResponse> SET_ABSENCE_PULSAsync(Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZLPE_EMPLOYEE_INFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pERNRField;
        
        private string aNSVHField;
        
        private string eKSCIField;
        
        private string bEGDAField;
        
        private string eNDDAField;
        
        private string pLSTXField;
        
        private string oRGTXField;
        
        private decimal eMPCTField;
        
        private bool eMPCTFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
                this.RaisePropertyChanged("PERNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ANSVH {
            get {
                return this.aNSVHField;
            }
            set {
                this.aNSVHField = value;
                this.RaisePropertyChanged("ANSVH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EKSCI {
            get {
                return this.eKSCIField;
            }
            set {
                this.eKSCIField = value;
                this.RaisePropertyChanged("EKSCI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BEGDA {
            get {
                return this.bEGDAField;
            }
            set {
                this.bEGDAField = value;
                this.RaisePropertyChanged("BEGDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ENDDA {
            get {
                return this.eNDDAField;
            }
            set {
                this.eNDDAField = value;
                this.RaisePropertyChanged("ENDDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PLSTX {
            get {
                return this.pLSTXField;
            }
            set {
                this.pLSTXField = value;
                this.RaisePropertyChanged("PLSTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ORGTX {
            get {
                return this.oRGTXField;
            }
            set {
                this.oRGTXField = value;
                this.RaisePropertyChanged("ORGTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal EMPCT {
            get {
                return this.eMPCTField;
            }
            set {
                this.eMPCTField = value;
                this.RaisePropertyChanged("EMPCT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMPCTSpecified {
            get {
                return this.eMPCTFieldSpecified;
            }
            set {
                this.eMPCTFieldSpecified = value;
                this.RaisePropertyChanged("EMPCTSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_LPE_WEB_GET_EMPLOYEE_INFO", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class GET_EMPLOYEE_INFORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_PERID;
        
        public GET_EMPLOYEE_INFORequest() {
        }
        
        public GET_EMPLOYEE_INFORequest(string IV_DATE, string IV_PERID) {
            this.IV_DATE = IV_DATE;
            this.IV_PERID = IV_PERID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_LPE_WEB_GET_EMPLOYEE_INFO.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class GET_EMPLOYEE_INFOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Infrastructure.KMDVacationService.KMD_FerieService.ZLPE_EMPLOYEE_INFO[] OT_EMPLOYEE_INFO;
        
        public GET_EMPLOYEE_INFOResponse() {
        }
        
        public GET_EMPLOYEE_INFOResponse(Infrastructure.KMDVacationService.KMD_FerieService.ZLPE_EMPLOYEE_INFO[] OT_EMPLOYEE_INFO) {
            this.OT_EMPLOYEE_INFO = OT_EMPLOYEE_INFO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_LPT_WEB_SET_ABSENCE_PULS", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SET_ABSENCE_PULSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BEGDA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BEGDA_OLD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BEGTI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BEGTI_OLD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ENDDA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ENDDA_OLD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ENDTI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ENDTI_OLD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_EXTRA_DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_OPERA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_PERNR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_SUBTY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_SUBTY_OLD;
        
        public SET_ABSENCE_PULSRequest() {
        }
        
        public SET_ABSENCE_PULSRequest(string IV_BEGDA, string IV_BEGDA_OLD, string IV_BEGTI, string IV_BEGTI_OLD, string IV_ENDDA, string IV_ENDDA_OLD, string IV_ENDTI, string IV_ENDTI_OLD, string IV_EXTRA_DATA, string IV_OPERA, string IV_PERNR, string IV_SUBTY, string IV_SUBTY_OLD) {
            this.IV_BEGDA = IV_BEGDA;
            this.IV_BEGDA_OLD = IV_BEGDA_OLD;
            this.IV_BEGTI = IV_BEGTI;
            this.IV_BEGTI_OLD = IV_BEGTI_OLD;
            this.IV_ENDDA = IV_ENDDA;
            this.IV_ENDDA_OLD = IV_ENDDA_OLD;
            this.IV_ENDTI = IV_ENDTI;
            this.IV_ENDTI_OLD = IV_ENDTI_OLD;
            this.IV_EXTRA_DATA = IV_EXTRA_DATA;
            this.IV_OPERA = IV_OPERA;
            this.IV_PERNR = IV_PERNR;
            this.IV_SUBTY = IV_SUBTY;
            this.IV_SUBTY_OLD = IV_SUBTY_OLD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_LPT_WEB_SET_ABSENCE_PULS.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SET_ABSENCE_PULSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Infrastructure.KMDVacationService.KMD_FerieService.BAPIRET2 OS_RETURN;
        
        public SET_ABSENCE_PULSResponse() {
        }
        
        public SET_ABSENCE_PULSResponse(Infrastructure.KMDVacationService.KMD_FerieService.BAPIRET2 OS_RETURN) {
            this.OS_RETURN = OS_RETURN;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LPT_VACAB_Service_OutChannel : Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LPT_VACAB_Service_OutClient : System.ServiceModel.ClientBase<Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out>, Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out {
        
        public LPT_VACAB_Service_OutClient() {
        }
        
        public LPT_VACAB_Service_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LPT_VACAB_Service_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LPT_VACAB_Service_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LPT_VACAB_Service_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFOResponse Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out.GET_EMPLOYEE_INFO(Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest request) {
            return base.Channel.GET_EMPLOYEE_INFO(request);
        }
        
        public Infrastructure.KMDVacationService.KMD_FerieService.ZLPE_EMPLOYEE_INFO[] GET_EMPLOYEE_INFO(string IV_DATE, string IV_PERID) {
            Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest inValue = new Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest();
            inValue.IV_DATE = IV_DATE;
            inValue.IV_PERID = IV_PERID;
            Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFOResponse retVal = ((Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out)(this)).GET_EMPLOYEE_INFO(inValue);
            return retVal.OT_EMPLOYEE_INFO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFOResponse> Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out.GET_EMPLOYEE_INFOAsync(Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest request) {
            return base.Channel.GET_EMPLOYEE_INFOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFOResponse> GET_EMPLOYEE_INFOAsync(string IV_DATE, string IV_PERID) {
            Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest inValue = new Infrastructure.KMDVacationService.KMD_FerieService.GET_EMPLOYEE_INFORequest();
            inValue.IV_DATE = IV_DATE;
            inValue.IV_PERID = IV_PERID;
            return ((Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out)(this)).GET_EMPLOYEE_INFOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSResponse Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out.SET_ABSENCE_PULS(Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest request) {
            return base.Channel.SET_ABSENCE_PULS(request);
        }
        
        public Infrastructure.KMDVacationService.KMD_FerieService.BAPIRET2 SET_ABSENCE_PULS(string IV_BEGDA, string IV_BEGDA_OLD, string IV_BEGTI, string IV_BEGTI_OLD, string IV_ENDDA, string IV_ENDDA_OLD, string IV_ENDTI, string IV_ENDTI_OLD, string IV_EXTRA_DATA, string IV_OPERA, string IV_PERNR, string IV_SUBTY, string IV_SUBTY_OLD) {
            Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest inValue = new Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest();
            inValue.IV_BEGDA = IV_BEGDA;
            inValue.IV_BEGDA_OLD = IV_BEGDA_OLD;
            inValue.IV_BEGTI = IV_BEGTI;
            inValue.IV_BEGTI_OLD = IV_BEGTI_OLD;
            inValue.IV_ENDDA = IV_ENDDA;
            inValue.IV_ENDDA_OLD = IV_ENDDA_OLD;
            inValue.IV_ENDTI = IV_ENDTI;
            inValue.IV_ENDTI_OLD = IV_ENDTI_OLD;
            inValue.IV_EXTRA_DATA = IV_EXTRA_DATA;
            inValue.IV_OPERA = IV_OPERA;
            inValue.IV_PERNR = IV_PERNR;
            inValue.IV_SUBTY = IV_SUBTY;
            inValue.IV_SUBTY_OLD = IV_SUBTY_OLD;
            Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSResponse retVal = ((Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out)(this)).SET_ABSENCE_PULS(inValue);
            return retVal.OS_RETURN;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSResponse> Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out.SET_ABSENCE_PULSAsync(Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest request) {
            return base.Channel.SET_ABSENCE_PULSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSResponse> SET_ABSENCE_PULSAsync(string IV_BEGDA, string IV_BEGDA_OLD, string IV_BEGTI, string IV_BEGTI_OLD, string IV_ENDDA, string IV_ENDDA_OLD, string IV_ENDTI, string IV_ENDTI_OLD, string IV_EXTRA_DATA, string IV_OPERA, string IV_PERNR, string IV_SUBTY, string IV_SUBTY_OLD) {
            Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest inValue = new Infrastructure.KMDVacationService.KMD_FerieService.SET_ABSENCE_PULSRequest();
            inValue.IV_BEGDA = IV_BEGDA;
            inValue.IV_BEGDA_OLD = IV_BEGDA_OLD;
            inValue.IV_BEGTI = IV_BEGTI;
            inValue.IV_BEGTI_OLD = IV_BEGTI_OLD;
            inValue.IV_ENDDA = IV_ENDDA;
            inValue.IV_ENDDA_OLD = IV_ENDDA_OLD;
            inValue.IV_ENDTI = IV_ENDTI;
            inValue.IV_ENDTI_OLD = IV_ENDTI_OLD;
            inValue.IV_EXTRA_DATA = IV_EXTRA_DATA;
            inValue.IV_OPERA = IV_OPERA;
            inValue.IV_PERNR = IV_PERNR;
            inValue.IV_SUBTY = IV_SUBTY;
            inValue.IV_SUBTY_OLD = IV_SUBTY_OLD;
            return ((Infrastructure.KMDVacationService.KMD_FerieService.LPT_VACAB_Service_Out)(this)).SET_ABSENCE_PULSAsync(inValue);
        }
    }
}
