// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Changedaccounttobankaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedaccounttobankaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201502201040378_Changed account to bank account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
