// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixedErrorInVacationReports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedErrorInVacationReports));
        
        string IMigrationMetadata.Id
        {
            get { return "201603212208171_FixedErrorInVacationReports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
